server:
  port: 8080

spring:
  profiles:
    active: pro
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://10.0.108.70:3306/db_ectp??useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  application:
    name: ectp


http:
  #最大连接数
  maxTotal : 100
  #并发数
  defaultMaxPerRoute : 20
  #创建连接的最长时间
  connectTimeout : 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout : 500
  #数据传输的最长时间
  socketTimeout : 10000
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled : true
