server:
  context-path: /dev



spring:
  datasource:
    url: jdbc:mysql://10.0.109.187:3306/db_ectp??useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true
