server:
  context-path: /pro



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_ectp??useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true
